service: parameter-store-replicator 

provider:
  name: aws
  runtime: nodejs18
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:GetParameter"
        - "ssm:PutParameter"
        - "ssm:GetParameterHistory"
        - "ssm:DeleteParameter"
        - "ssm:DeleteParameters"
      Resource: "*"

functions:
  replicate:
    environment: 
      AWS_TARGET_REGION: ${opt:target}
    handler: index.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"

